name: Push to branches

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

env:
  CCK_BASIC_INFRA_DIRECTORY_PATH: "${{ vars.COMMON_SHORT_NAME }}/basic-infra"
  AWS_REGION: "us-east-2"
  WORKSPACE: "prod"

jobs:
  ### Confluent Cloud Kafka Infrastructure creation for PROD ###
  create_cck_basic_infra_prod:
    if: github.event.pull_request.merged == true
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-to-aws/create
        with:
          aws_account_number: ${{ vars.AWS_ACCOUNT_NUMBER }}
          aws_github_oidc_role: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}
          aws_region: ${{ env.AWS_REGION }}
          terraform_workspace: ${{ env.WORKSPACE }}
          cc_api_key: ${{ secrets.CC_API_KEY }}
          cc_api_secret: ${{ secrets.CC_API_SECRET }}
          common_short_name: ${{ vars.COMMON_SHORT_NAME }}
          tf_directory_path: ${{ env.CCK_BASIC_INFRA_DIRECTORY_PATH }}
          deploy: true
